import { type NextPage } from "next";
import Head from "next/head";

import { api } from "~/utils/api";
import { SignIn, SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { Button } from "~/components/ui/button";

const Home: NextPage = () => {
  const user = useUser();
  const { data } = api.posts.getAll.useQuery();
  console.log(data);
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div >
          <h1 >
            seeter
          </h1>
          <SignIn path="/sign-in" routing="path" signUpUrl="/sign-up" />
          <div>
            {!user.isSignedIn && <SignInButton />}
            {user.isSignedIn && (
              <SignOutButton>
                <Button variant={"secondary"}>Sign out!</Button>
              </SignOutButton>
            )}
          </div>
          <div>
            <h2>Posts</h2>
            <div>
              {data?.map((post) => (
                <div key={post.id}>{post.content}</div>
              ))}
            </div>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
