import { type NextPage } from "next";
import Head from "next/head";

import { api } from "~/utils/api";
import { SignIn, SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { Button } from "~/components/ui/button";
import { Input } from "~/components/ui/input";
import { Avatar, AvatarFallback, AvatarImage } from "~/components/ui/avatar";

const PostCreator = () => {
  // eslint-disable-next-line react-hooks/rules-of-hooks
  const { user } = useUser();
  if (!user) return null;

  return (
    <div className="m-2 flex">
      <Avatar>
        <AvatarImage src={user.profileImageUrl} alt="Profile image" />
        <AvatarFallback>???</AvatarFallback>
      </Avatar>

      <Input placeholder="Seethe!" type="text" />
    </div>
  );
};

const Home: NextPage = () => {
  const user = useUser();
  const { data } = api.posts.getAll.useQuery();
  console.log(data);
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <h1>seeter</h1>

          <PostCreator />
          <div>
            <h2>Posts</h2>
            <div>
              {data?.map((post) => (
                <div key={post.id}>{post.content}</div>
              ))}
            </div>
          </div>
        </div>
        <SignIn path="/sign-in" routing="path" signUpUrl="/sign-up" />
        <div>
          {!user.isSignedIn && <SignInButton />}
          {user.isSignedIn && (
            <SignOutButton>
              <Button variant={"secondary"}>Sign out!</Button>
            </SignOutButton>
          )}
        </div>
      </main>
    </>
  );
};

export default Home;
